<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.0.6</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>dev.orion</groupId>
	<artifactId>track-my-vehicle-employee-service</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>

	<properties>
		<java.version>21</java.version>
		<common.version>1.0-SNAPSHOT</common.version>
		<ez-sender.client.version>1.0-SNAPSHOT</ez-sender.client.version>
		<core.domain.version>1.0-SNAPSHOT</core.domain.version>
		<employee.core.domain.version>0.0.1-SNAPSHOT</employee.core.domain.version>
	</properties>

	<modules>
		<module>user-core-domain</module>
		<module>user-service-main-application</module>
	</modules>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>dev.orion</groupId>
				<artifactId>track-my-vehicle-commons</artifactId>
				<version>${common.version}</version>
			</dependency>

			<dependency>
				<groupId>dev.orion</groupId>
				<artifactId>track-my-vehicle-core-domain</artifactId>
				<version>${core.domain.version}</version>
			</dependency>

			<dependency>
				<groupId>dev.orion</groupId>
				<artifactId>user-core-domain</artifactId>
				<version>${employee.core.domain.version}</version>
			</dependency>

			<dependency>
				<groupId>dev.orion</groupId>
				<artifactId>ez-sender-client</artifactId>
				<version>${ez-sender.client.version}</version>
			</dependency>

			<dependency>
				<groupId>org.springframework.grpc</groupId>
				<artifactId>spring-grpc-dependencies</artifactId>
				<version>1.0.3</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

</project>