server.port=8082
server.servlet.context-path=/employee-api

# gRPC config
spring.grpc.client.channels.auth-service.address=static://localhost:9090
spring.grpc.client.channels.noti-service.address=static://localhost:9001

spring.datasource.url=jdbc:postgresql://localhost:5432/employee-service-db
spring.datasource.username=orion
spring.datasource.password=password#123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.properties.hibernate.dialect=org.postgresql.Driver
spring.jpa.hibernate.properties.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

app.security.white.list=/public/**,/auth/**

app.email.domain.name=gmail.com