server.port=8082
server.servlet.context-path=/employee-api

# gRPC config
spring.grpc.client.channels.auth-service.address=static://localhost:9090
spring.grpc.client.channels.noti-service.address=static://localhost:9001

spring.datasource.url=jdbc:postgresql://ep-solitary-frost-ao2zo5hv-pooler.c-2.ap-southeast-1.aws.neon.tech/employee-service-db
spring.datasource.username=neondb_owner
spring.datasource.password=npg_jfH6DFKU3xRA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.properties.hibernate.dialect=org.postgresql.Driver
spring.jpa.hibernate.properties.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

app.security.white.list=/public/**,/auth/**,/error

app.email.domain.name=gmail.com

# oauth
spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:certs/public-key.pem